---
dependency:
  name: galaxy
  options:
    force: True
driver:
  name: docker
platforms:
  - name: basic
    image: archlinux
    dockerfile: Dockerfile.j2
    pull: false
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - lint
    - create
    - prepare
    - converge
    - verify
    - destroy
